---
name: Make
'on':
  pull_request:
  push:
    branches:
      - master
      - ubuntu-dock

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install dependencies.
        run: sudo apt-get install -y sassc gettext

      - name: Make
        run: make

      - name: Make Install
        run: make install
